version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  engineeringunitscore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development