version: '3.4'

services:
  nginx-proxy:
    image: nginx
    depends_on:
      - api
      - engineeringunitscore
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - routing_net

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
    networks:
      - prom_net

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    expose:
      - 80
    networks:
      - prom_net
      - routing_net
      - inner_net

  engineeringunitscore:
    image: ${DOCKER_REGISTRY-}engineeringunitscore
    build:
      context: .
      dockerfile: EngineeringUnitsCore/Dockerfile
    expose:
      - 80
    volumes:
      - ./EngineeringUnitsCore/Data/poscUnits22.xml:/app/Data/poscUnits22.xml
    networks:
      - inner_net

networks:
  prom_net:
  routing_net:
  inner_net: